### ISSUE TITLE
[Bug] Exception with JavaGP examples [sf#12]

### ISSUE THREAD

**Issue by meneguzzi** [pucrs-automated-planning/javagp#12]
**Reported by elpaquitooo on 2015-05-09 11:32 UTC**
I'm starting to use this application, use the examples as shown in the help, but the application produces exceptions.

I Run: java -jar javagp.jar -nopddl -d examples/strips/ma-prodcell/domain.txt -p examples/strips/ma-prodcell/problem.txt

I get the following result:

INFORMACIÓN: Running planner, maximum memory: 247,5MB
INFORMACIÓN: Expanding graph
INFORMACIÓN: Goals not possible with 1 steps
INFORMACIÓN: Expanding graph
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at graphplan.graph.memo.mutexes.MutexCondition.verifyConditionsByIndexes(MutexCondition.java:30)
    at graphplan.graph.memo.mutexes.StaticMutexesTable.isMutex(StaticMutexesTable.java:130)
    at graphplan.graph.algorithm.impl.MutexGeneratorImpl.addActionMutexes(MutexGeneratorImpl.java:63)
    at graphplan.graph.planning.PlanningGraph.expandGraph(PlanningGraph.java:229)
    at graphplan.Graphplan.plan(Graphplan.java:386)
    at graphplan.Graphplan.main(Graphplan.java:237)

**Comment by meneguzzi** [comment]
**Updated by meneguzzi on 2015-06-19 22:27 UTC**
- **status**: unread --> accepted
- **assigned_to**: Ramon Fraga Pereira

**Comment by meneguzzi** [comment]
**Commented by meneguzzi on 2015-06-19 22:27 UTC**
The bug seems to occur in the memoized mutexes bit implemented by Ramon. I'm assigning the bug to him.
