### ISSUE TITLE
[Bug] Parse error in PDDL Domain examples [sf#15]

### ISSUE THREAD

**Issue by meneguzzi** [pucrs-automated-planning/javagp#15]
**Reported by beppe712 on 2015-10-11 15:30 UTC**
It seems when running any example problem with any key requirement other than :strips JavaGP will throw the error:

MacBook-Pro-di-Giuseppe:javagp-bin-1-2 Beppe$ java -jar javagp.jar -d examples/pddl/blocksworld/blocksworld.pddl -p examples/pddl/blocksworld/pb1.pddl
GRAVE: Parser error at line 2, column 24 file (blocksworld.pddl) : Require key ":equality" forbidden due to parser requirement options.
pddl4j.ParserException: Parse error in PDDL Domain
    at graphplan.parser.PDDLPlannerAdapter.<init>(PDDLPlannerAdapter.java:106)
    at graphplan.Graphplan.main(Graphplan.java:195)

JavaGP will successfully find a plan in the case of Blocksworld without :equality. The same error applies to any other key, listing "Require key ":name-of-key" forbidden due to parser requirement options." for each key.

Best Regards

**Comment by meneguzzi** [comment]
**Commented by meneguzzi on 2015-10-17 22:35 UTC**
This is not necessarily a bug, since it is stopping the parser when you state that you need something the parser cannot do. The erro might have been in the PDDL, but before I close this bug, I want to make sure you agree with my interpretation.

**Comment by meneguzzi** [comment]
**Updated by meneguzzi on 2015-10-17 22:36 UTC**
- **status**: unread --> pending
- **assigned_to**: Felipe Meneguzzi

**Comment by meneguzzi** [comment]
**Updated by meneguzzi on 2015-10-17 22:38 UTC**
- **status**: pending --> accepted

**Comment by meneguzzi** [comment]
**Commented by meneguzzi on 2015-10-17 22:38 UTC**
I will try to work this problem tonight.
