### ISSUE TITLE
ArithExpr: first operand 'swap' is not numeric or variable.

### ISSUE THREAD

**Issue by pedrovanzella** [pucrs-automated-planning/javagp#24]
I'm not quite sure what is causing this, but I'm seeing this error message:

```
SEVERE: --> The Problem has Negative Preconditions

SEVERE: Error parsing structure swap-vjason.asSyntax.parser.ParseException: [null:1] ArithExpr: first operand 'swap' is not numeric or variable.
        at jason.asSyntax.parser.as2j.arithm_expr(as2j.java:1278)
        at jason.asSyntax.parser.as2j.rel_expr(as2j.java:1155)
        at jason.asSyntax.parser.as2j.log_expr_factor(as2j.java:1121)
        at jason.asSyntax.parser.as2j.log_expr_trm(as2j.java:1086)
        at jason.asSyntax.parser.as2j.log_expr(as2j.java:1069)
        at jason.asSyntax.parser.as2j.term(as2j.java:950)
        at jason.asSyntax.Structure.parse(Structure.java:85)
        at graphplan.domain.jason.OperatorImpl.<init>(OperatorImpl.java:59)
        at graphplan.parser.PDDLPlannerAdapter.getDomainDescriptionFromPddlObject(PDDLPlannerAdapter.java:152)
        at graphplan.Graphplan.main(Graphplan.java:196)

Exception in thread "main" java.lang.NullPointerException
        at jason.asSyntax.Atom.<init>(Atom.java:49)
        at jason.asSyntax.Structure.<init>(Structure.java:64)
        at graphplan.domain.jason.OperatorImpl.<init>(OperatorImpl.java:59)
        at graphplan.parser.PDDLPlannerAdapter.getDomainDescriptionFromPddlObject(PDDLPlannerAdapter.java:152)
        at graphplan.Graphplan.main(Graphplan.java:196)
```

The `swap-v` action mentioned in the error message is as follows:

```
(:action swap-v
    :parameters (?pos1 ?house1 ?pos2 ?house2)
    :precondition (and
                   (tile ?pos1 ?house1)
                   (tile ?pos2 ?house2)
                   (vadj ?pos1 ?pos2)
                  )
    :effect (and
              (tile ?pos1 ?house2)
              (not (tile ?pos1 ?house1))
              (tile ?pos2 ?house1)
              (not (tile ?pos2 ?house2))
            )
  )
```

Let me know if you'd like to have the full pddls. I'm not posting them as they refer to an ongoing class assignment.

Just for the record, these PDDLs won't work on the web-planner either, but they do work on planning.domains, and generate a proper plan.

**Comment by ramonpereira** [comment]
This error occurs due to the use of "-" on operators (and predicates) definition.
Please, try to rename the operator definition to swap_v.

**Comment by pedrovanzella** [comment]
Huh, that works! Thanks!
