### ISSUE TITLE
Planner fails to find a trivial solution.

### ISSUE THREAD

**Issue by AlessandroBono** [pucrs-automated-planning/javagp#25]
I've written a simple planning problem to test JavaGP and the planner fails to find the solution. Since JavaGP works for the `blockworld` example in `examples/pddl`, I suspect that the planner fails due to the presence of actions without parameters.

Follow the domain and problem definitions:
domain0.pddl
```
(define (domain domain0)
  (:predicates (oo)
               (pp)
               (qq))
  (:action firstAction  :parameters () :precondition (oo) :effect (and (not (oo)) (pp)))
  (:action secondAction :parameters () :precondition (pp) :effect (and (not (pp)) (qq)))
)
```

problem0.pddl
```
(define (problem problem0)
  (:domain domain0)
  (:init (oo))
  (:goal (qq))
)
```

The output received is the following:
```
$ java -jar javagp.jar -d examples/dummy/domain0.pddl -p examples/dummy/problem0.pddl
INFO: Running planner, maximum memory: 3,851.25MB
INFO: Expanding graph
INFO: Goals not possible with 1 steps
INFO: Expanding graph
INFO: Goals not possible with 2 steps
graphplan.graph.planning.PlanningGraphException: At graph level 4: Goals are not possible and graph has levelled off, plan is not possible.
	at graphplan.Graphplan.plan(Unknown Source)
	at graphplan.Graphplan.getPlanSolution(Unknown Source)
	at graphplan.Graphplan.main(Unknown Source)
```

**Comment by meneguzzi** [comment]
Thanks Alessandro for the detailed bug report. It does look like a problem. I will follow this up debugging the planner ASAP and get back to you here.
